runtime: nodejs12

env_variables:
  SERVER_PORT: 8080

name: Deploy to App Engine
uses: google-github-actions/deploy-appengine@v0.4.0

name: Authenticate to Google Cloud
uses: google-github-actions/auth@v0.4.3
