name: Deployment

on:
  push:
    branches:
    - master
  
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: birthday-1209
          version: master
          credentials: ${{secrets.SIVAKANNA_IN_BIRTHDAY_1209}}
          flags: --no-cache
          deliverables: app.yaml